import { Roboto } from "next/font/google";


const roboto = Roboto({ weight: ["300","500","700","900"],
  subsets: ["latin"] });

export const metadata = {
  title: "Projeto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
